//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.11.09 at 11:28:17 PM CST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ibm.com/cloud/trip", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package application.com.ibm.cloud.trip;
